name: on-demand-test

on:
  issue_comment:
    types:
      - created

jobs:
  on-demand-test:
    if: |
      github.event.comment.author_association == 'COLLABORATOR'
      && github.event.issue.pull_request != 0
      && github.event.issue.closed_at == 0
      && github.event.issue.locked == 0
      && github.event.comment.body == 'run tests'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Get the base branch of the PR
        run: |
          echo Requesting PR base branch...
          branch=$(curl $PR_URL | jq -r '.head.ref')
          echo PR base branch: $branch
          echo "::set-env name=BRANCH::$branch"
        env:
          PR_URL: ${{ github.event.issue.pull_request.url }}

      - name: Checkout the base branch
        run: |
          git clone --branch=$BRANCH --depth=1 $REPO_URL .
        env:
          REPO_URL: ${{ github.repositoryUrl }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        run: |
          npm test
          ec=$?
          echo "::set-env name=EXIT_CODE::$ec"
        env:
          CI: true

      - name: Report back to the comment thread with the results
        run: |
          workflowUrl=https://github.com/sonicoriginalsoftware/jester/actions/runs/$RUN_ID
          echo Workflow URL: $workflowUrl
          
          textStatus=$(( $EXIT_CODE == 0 )) && '**Passed**' || '**Failed**'

          echo Status: $textStatus

          curl --request POST --url $COMMENTS_URL \
            --header 'authorization: Bearer $TOKEN' \
            --header 'content-type: application/json' \
            --data '{ "body": "[$textStatus]($workflowUrl)" }'
        env:
          RUN_ID: ${{ github.run_id }}
          COMMENTS_URL: ${{ github.event.issue.comments_url }}
          TOKEN: ${{ github.token }}

