name: master

on:
  pull_request:
    branches:
      - "master"
    types:
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true

  publish:
    needs: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get git info
        run: |
          git rev-parse --abbrev-ref HEAD
          git remote --verbose
          git checkout

      - name: Configure git
        run: |
          git config user.email 'engineer.nblair@gmail.com'
          git config user.name "Nathan Blair"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install and generate docs
      - run: |
          npm ci
          npx jsdoc -R README.md -P package.json -d docs lib/*

      - name: Git Commit
        run: |
          git add docs
          git commit -m "Updated documentation"

      - run: npm version patch

      - run: git log -n 3

      # FIXME
      - run: git push origin master

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Increment npm version on dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
        run: |
          npm version patch
          git push origin dev

